### ISSUE TITLE
v1.0 roadmap

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/nova-dprint#2]
- [x] Implement configuration
    - [x] User-level (fc392853)
    - [x] Project-level (a88b984f)
- [ ] Implement formatting
    - [x] Whole documents (e4436b6d)
    - [ ] Ranges
- [ ] Get dprint
    - [ ] From a project installation
    - [ ] From a global installation
    - [x] From a configured version (fc392853 and e4436b6d)
    - [ ] #3
- [ ] #4
- [x] Logo (ad287080)
